### ISSUE TITLE
Warned user message lacks context

### ISSUE THREAD

**Issue by ScarletQuiver** [Capybara-Modders/freja-public-repo#1]
The message that the user receives from Freja as a DM is pretty dry: just the plaintext of the warning with zero context. It would be lovely if the text that the user receives was a bit more verbose, for example:

> You have received a warning from the official Valheim server:
> _[warning text in italics]_
> If you wish to discuss this warning, please message Modmail directly and open a ticket.

**Comment by Noitabara** [comment]
Implemented!
